dist: trusty
sudo: require

language: cpp
compiler: gcc

install:
  - sudo apt-get install libboost-system1.55-dev libboost-thread1.55-dev libboost-log1.55-dev

script:
- mkdir build
- cd build && cmake ..
- make -j8

# branches whitelist
branches:
  only:
  - master
